### ISSUE TITLE
"Add Data" Button not working

### ISSUE THREAD

**Issue by cvg6** [databrary/datavyu#314]
Windows 10 Enterprise LTSB, 
Upgraded to Datavyu 1.5.1. 
Can't open previously saved files. 
The "Add Data" button is not working on the controller.   Happening on multiple computers connected to the same domain and across all users   Datavyu is installed in the c:\users\public location so all users have access.   
Other buttons on the controller screen seem to work fine.

**Comment by TheoWolf** [comment]
@cvg6 Can you please share the log file in c:\users\public\datavyu\app\all.log
If you were enable to open a video, means that Datavyu cannot find the right dependencies for the Media Players, I would recommend installing Datavyu in the default folder and test it out.

**Comment by cvg6** [comment]
Thanks.  I will try to get the log today.  Also, tried to install in the default directory with the same result.

**Comment by cvg6** [comment]
[all.log](https://github.com/databrary/datavyu/files/3843128/all.log)

**Comment by TheoWolf** [comment]
@cvg6 It should be fixed now, could you please try and let me know.

**Comment by cvg6** [comment]
What is fixed now?   
Sorry, I don't understand

**Comment by TheoWolf** [comment]
Yes, it should be fixed, the problem was not from your computers or used Datavyu version but from our servers, datavyu fetch the latest pre-release version from our server at launch and that version was outdated.  I just had to update the pre-release version on our server.
Let me know if you were able to open Datavyu on your PCs

**Comment by cvg6** [comment]
Ok. Should I download the software again?

**Comment by TheoWolf** [comment]
No, the one installed on your machine should work now, if not, please let me know.

**Comment by cvg6** [comment]
Ok.  I will try again in the morning

**Comment by cvg6** [comment]
Hi.  I tested again with no change.   The "Add Data" button still does nothing.  Does DataVyu require access to a website?   The computers are locked down for security reasons and I didn't think I needed internet access to use DataVyu?   Today's log file is attached. 
[all.log](https://github.com/databrary/datavyu/files/3851899/all.log)

**Comment by TheoWolf** [comment]
@cvg6 Indeed, Datavyu requires access to the Internet in order to check the latest version, this might be your problem, please hook your system to the internet and let me know if this helps. If not, please send me an email at info@datavyu.org , I will be more than happy to get in touch via Skype and troubleshoot the problem.

**Comment by TheoWolf** [comment]
I opened a ticket to fix this issue, a new release candidate will be available early next week.

**Comment by cvg6** [comment]
Perfect!   Thank you .

**Comment by cvg6** [comment]
Will I be notified when the new RC is available?

**Comment by TheoWolf** [comment]
The new RC is out, please check http://www.datavyu.org/download.html.
The release notes are here https://github.com/databrary/datavyu/releases

**Comment by TheoWolf** [comment]
Please let me know if the issue is fixed with Datavyu-1.5.1-RC3 version.

**Comment by cvg6** [comment]
@TheoWolf   Thank you very much.  The issue is fixed with 1.5.1-RC3.   I really appreciate you help.
